# Filename: ${XDG_CONFIG_HOME}/alacritty/alacritty.toml
# Soft-linked from /mnt/shared/documents/dotFiles/alacritty.toml
#
# Modifies attributes for alacritty terminal

general.live_config_reload = true

[font]
size = 12

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Italic"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[keyboard]
bindings = [ { key = "+", mods = "Control", action = "IncreaseFontSize" },
             { key = "-", mods = "Control", action = "DecreaseFontSize" } ]
