live_config_reload = true

[font]
size = 10.0

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"
