# Filename: ${XDG_CONFIG_HOME}/alacritty/alacritty.toml
# Soft-linked from /mnt/shared/documents/dotFiles/alacritty.toml

general.live_config_reload = true

[font]
size = 12

[font.normal]
family = "Terminus"
style = "Regular"

[font.bold]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Italic"

[font.bold_italic]
family = "Terminus"
style = "Bold Italic"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
