#!/bin/sh

# Filename: ${XDG_CONFIG_HOME}/i3blocks/i3blocks_volume
# Soft-linked from /mnt/shared/documents/dotFiles/i3blocks_volume

mute=`pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f 2`
if [ "$mute" == "no" ]
then
  val=`pactl get-sink-volume @DEFAULT_SINK@ | grep dB | cut -d % -f 3 | cut -d '/' -f 2`
  echo " "$val
else
  echo " [mute]"
fi
