worker_processes  1;

# Load all installed modules
include modules.d/*.conf;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;

    server {
        server_name  samueljdunham.com www.samueljdunham.com;
        root /var/www/samueljdunham.com/html;
	location / {
          index index.html;
        }
    
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/samueljdunham.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/samueljdunham.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }

    server {
        server_name  jellyfin.samueljdunham.com;
	location / {
	    proxy_pass http://10.0.1.2:8096;
	}
    
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/samueljdunham.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/samueljdunham.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }

    server {
        listen       21731;
        server_name  localhost;

        root /var/www/dunhamsjjngya447ule7anz64rpezkpqi3kciwa7rlh6xgdkkm5jgvyd.onion/html;
    }

    server {
        if ($host = www.samueljdunham.com) {
            return 301 https://$host$request_uri;
        } # managed by Certbot
    
    
        if ($host = samueljdunham.com) {
            return 301 https://$host$request_uri;
        } # managed by Certbot
    
    
        listen       80;
        server_name  samueljdunham.com www.samueljdunham.com;
        return 404; # managed by Certbot
    }

    server {
        if ($host = jellyfin.samueljdunham.com) {
            return 301 https://$host$request_uri;
        } # managed by Certbot


        listen       80;
        server_name  jellyfin.samueljdunham.com;
        return 404; # managed by Certbot
    }
}
