#!/bin/sh

# Filename: ${HOME}/.config/tigervnc/xstartup
# Soft-linked from /mnt/shared/documents/dotFiles/xstartup

unset SESSION_MANAGER

unset DBUS_SESSION_BUS_ADDRESS

# Filename: ${HOME}/.config/tigervnc/xstartup

# Disable screensaver
xset s off
xset -dpms

# Set keyboard key repeat rate
xset r rate 500 40
xset -r 26 # Stop `e` key from auto-repeating

# Start picom using custom conf file
picom --config ${XDG_CONFIG_HOME}/picom/picom.conf &

# Use two monitors, not mirrored
#xrandr --output HDMI-1 --auto --right-of DP-1 &

# Execute window manager
exec i3 -c ${XDG_CONFIG_HOME}/i3/config
